# =========================================================
# Profile PROD: PostgreSQL via environment variable, validate DDL
# Credential via env var: DB_URL, DB_USERNAME, DB_PASSWORD, JWT_SECRET
# =========================================================

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${DB_URL}
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}

app.jwt.secret=${JWT_SECRET}

quarkus.hibernate-orm.database.generation=validate
quarkus.hibernate-orm.log.sql=false

quarkus.log.console.level=INFO
quarkus.log.file.level=INFO
quarkus.log.category."com.example.template.quarkus".level=INFO
